apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos1
  labels:
    app: centos1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: centos1
  template:
    metadata:
      labels:
        app: centos1
    spec:
      containers:
      - name: centos1
        image: kalyanreddy932/sample_web_cent7
        ports:
        - containerPort: 80